version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"    # RabbitMQ default
      - "15672:15672"  # RabbitMQ management UI
    restart: unless-stopped

volumes:
  mongo-data:
