# Use the official Nginx image
FROM nginx:alpine

# Copy the contents of the dist folder to Nginx's default directory
COPY dist/apps/products-frontend /usr/share/nginx/html

# Expose port 80
EXPOSE 80
